name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the main branch
  push:
    branches:
    - main
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            generated/github-contribution-grid-snake.svg
            generated/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      # Upload the generated SVG files as an artifact
      - name: Upload SVG files
        uses: actions/upload-artifact@v2
        with:
          name: generated-svgs
          path: generated
      
  move_to_assets:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      # Download the generated SVG files artifact
      - name: Download SVG files
        uses: actions/download-artifact@v2
        with:
          name: generated-svgs
          path: generated
      
      # Move the generated SVG files to the assets folder in the main branch
      - name: Move SVG files to assets folder
        run: mv generated/* assets/
