# Example workflow to generate and push files, and upload artifacts with a specific upload path
name: Generate, Push, and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  generate_push_and_upload:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      # Step 1: Generate the SVG files
      - name: Generate SVG files
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: GIT commit and push docs
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "alexandermfisher@users.noreply.github.com"
          git add docs
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
