name: Generate and Push Files

on:
  # Run the workflow on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate_and_push:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Generate the SVG files
      - name: Generate SVG files
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark
